export enum EvaluationOutcome {
  PASS = "PASS",
  WARNING_DEVIATION = "WARNING_DEVIATION",
  CRITICAL_LOW_OR_SHORT = "CRITICAL_LOW_OR_SHORT",
  OPEN_LINE_OL = "OPEN_LINE_OL",
  UNEXPECTED_HIGH = "UNEXPECTED_HIGH",
}
